version: '3'

services:
  main:
    image: shiftinv/github-webhook-filter
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      HOSTNAME: "0.0.0.0"
      ADDR: "${ADDR:-127.0.0.1}"
      PORT: "${PORT:-8080}"
    ports:
      - '${ADDR:-127.0.0.1}:${PORT:-8080}:${PORT:-8080}'
    command:
      - run
      - --allow-env
      - --allow-net=:${PORT},discord.com
      - main.ts
